name = "cloudflare-worker-ai-rust-example"
main = "build/index.js"
compatibility_date = "2025-09-27"

[build]
command = "cargo install -q worker-build && worker-build --release"

[ai]
binding = "AI"

[[services]]
binding = "MCP_USERS"
service = "your-mcp-service"

[vars]
MODEL_AI = "your-ai-model-binding"
